import type { Company } from "@/lib/types";

export const COMPANIES: Company[] = [
  { slug: "okta", name: "Okta", ats: "greenhouse", token: "okta", website: "https://www.okta.com", hq: "San Francisco, USA", industry: "Identity" },
  { slug: "databricks", name: "Databricks", ats: "greenhouse", token: "databricks", website: "https://www.databricks.com", hq: "San Francisco, USA", industry: "Data & AI" },
  { slug: "mongodb", name: "MongoDB", ats: "greenhouse", token: "mongodb", website: "https://www.mongodb.com", hq: "New York, USA", industry: "Database" },
  { slug: "zscaler", name: "Zscaler", ats: "greenhouse", token: "zscaler", website: "https://www.zscaler.com", hq: "San Jose, USA", industry: "Security" },
  { slug: "stripe", name: "Stripe", ats: "greenhouse", token: "stripe", website: "https://stripe.com", hq: "South San Francisco, USA", industry: "Payments" },
  { slug: "point72", name: "Point72", ats: "greenhouse", token: "point72", website: "https://www.point72.com", hq: "Stamford, USA", industry: "Investment" },
  { slug: "gitlab", name: "GitLab", ats: "greenhouse", token: "gitlab", website: "https://about.gitlab.com", hq: "Remote", industry: "DevTools" },
  { slug: "toast", name: "Toast", ats: "greenhouse", token: "toast", website: "https://pos.toasttab.com", hq: "Boston, USA", industry: "Fintech" },
  { slug: "twilio", name: "Twilio", ats: "greenhouse", token: "twilio", website: "https://www.twilio.com", hq: "San Francisco, USA", industry: "Communications" },
  { slug: "smartsheet", name: "Smartsheet", ats: "greenhouse", token: "smartsheet", website: "https://www.smartsheet.com", hq: "Bellevue, USA", industry: "Productivity" },
  { slug: "airbnb", name: "Airbnb", ats: "greenhouse", token: "airbnb", website: "https://www.airbnb.com", hq: "San Francisco, USA", industry: "Travel" },
  { slug: "roblox", name: "Roblox", ats: "greenhouse", token: "roblox", website: "https://www.roblox.com", hq: "San Mateo, USA", industry: "Gaming" },
  { slug: "khan-academy", name: "Khan Academy", ats: "greenhouse", token: "khanacademy", website: "https://www.khanacademy.org", hq: "Mountain View, USA", industry: "Education" },
  { slug: "sumo-logic", name: "Sumo Logic", ats: "greenhouse", token: "sumologic", website: "https://www.sumologic.com", hq: "Redwood City, USA", industry: "Observability" },
  { slug: "postman", name: "Postman", ats: "greenhouse", token: "postman", website: "https://www.postman.com", hq: "San Francisco, USA", industry: "DevTools" },
  { slug: "coinbase", name: "Coinbase", ats: "greenhouse", token: "coinbase", website: "https://www.coinbase.com", hq: "Remote", industry: "Crypto" },
  { slug: "imc", name: "IMC", ats: "greenhouse", token: "imc", website: "https://www.imc.com", hq: "Amsterdam, Netherlands", industry: "Trading" },
  { slug: "smartbear", name: "SmartBear", ats: "greenhouse", token: "smartbear", website: "https://smartbear.com", hq: "Somerville, USA", industry: "DevTools" },
  { slug: "new-relic", name: "New Relic", ats: "greenhouse", token: "newrelic", website: "https://newrelic.com", hq: "San Francisco, USA", industry: "Observability" },
  { slug: "elastic", name: "Elastic", ats: "greenhouse", token: "elastic", website: "https://www.elastic.co", hq: "Amsterdam, Netherlands", industry: "Search" },
  { slug: "datadog", name: "Datadog", ats: "greenhouse", token: "datadog", website: "https://www.datadoghq.com", hq: "New York, USA", industry: "Observability" },
  { slug: "worldquant", name: "WorldQuant", ats: "greenhouse", token: "worldquant", website: "https://www.worldquant.com", hq: "Old Greenwich, USA", industry: "Quantitative" },
  { slug: "adyen", name: "Adyen", ats: "greenhouse", token: "adyen", website: "https://www.adyen.com", hq: "Amsterdam, Netherlands", industry: "Payments" },
  { slug: "waymo", name: "Waymo", ats: "greenhouse", token: "waymo", website: "https://waymo.com", hq: "Mountain View, USA", industry: "Autonomy" },
  { slug: "ping-identity", name: "Ping Identity", ats: "greenhouse", token: "pingidentity", website: "https://www.pingidentity.com", hq: "Denver, USA", industry: "Identity" },
  { slug: "coursera", name: "Coursera", ats: "greenhouse", token: "coursera", website: "https://www.coursera.org", hq: "Mountain View, USA", industry: "Education" },
  { slug: "vercel", name: "Vercel", ats: "greenhouse", token: "vercel", website: "https://vercel.com", hq: "San Francisco, USA", industry: "Cloud" },
  { slug: "cloudflare", name: "Cloudflare", ats: "greenhouse", token: "cloudflare", website: "https://www.cloudflare.com", hq: "San Francisco, USA", industry: "Internet" },
  { slug: "jump-trading", name: "Jump Trading", ats: "greenhouse", token: "jumptrading", website: "https://www.jumptrading.com", hq: "Chicago, USA", industry: "Trading" },
  { slug: "figma", name: "Figma", ats: "greenhouse", token: "figma", website: "https://www.figma.com", hq: "San Francisco, USA", industry: "Design" },
  { slug: "amplitude", name: "Amplitude", ats: "greenhouse", token: "amplitude", website: "https://amplitude.com", hq: "San Francisco, USA", industry: "Analytics" },
  { slug: "scale-ai", name: "Scale AI", ats: "greenhouse", token: "scaleai", website: "https://scale.com", hq: "San Francisco, USA", industry: "AI" },
  { slug: "anthropic", name: "Anthropic", ats: "greenhouse", token: "anthropic", website: "https://www.anthropic.com", hq: "San Francisco, USA", industry: "AI" },
  { slug: "mixpanel", name: "Mixpanel", ats: "greenhouse", token: "mixpanel", website: "https://mixpanel.com", hq: "San Francisco, USA", industry: "Analytics" },
  { slug: "snowflake", name: "Snowflake", ats: "ashby", token: "snowflake", website: "https://www.snowflake.com", hq: "Bozeman, USA", industry: "Data Cloud" },
  { slug: "cerebras", name: "Cerebras", ats: "ashby", token: "cerebras", website: "https://www.cerebras.ai", hq: "Sunnyvale, USA", industry: "AI Hardware" },
  { slug: "openai", name: "OpenAI", ats: "ashby", token: "openai", website: "https://openai.com", hq: "San Francisco, USA", industry: "AI" },
  { slug: "cursor", name: "Cursor", ats: "ashby", token: "cursor", website: "https://cursor.com", hq: "San Francisco, USA", industry: "AI" },
  { slug: "notion", name: "Notion", ats: "ashby", token: "notion", website: "https://www.notion.so", hq: "San Francisco, USA", industry: "Productivity" },
  { slug: "temporal", name: "Temporal", ats: "ashby", token: "temporal", website: "https://temporal.io", hq: "Seattle, USA", industry: "Infrastructure" },
  {
    slug: "nvidia",
    name: "NVIDIA",
    ats: "workday",
    website: "https://www.nvidia.com",
    hq: "Santa Clara, USA",
    industry: "Semiconductors",
    workday: { host: "nvidia.wd5.myworkdayjobs.com", tenant: "nvidia", site: "NVIDIAExternalCareerSite" },
  },
  {
    slug: "intel",
    name: "Intel",
    ats: "workday",
    website: "https://www.intel.com",
    hq: "Santa Clara, USA",
    industry: "Semiconductors",
    workday: { host: "intel.wd1.myworkdayjobs.com", tenant: "intel", site: "External" },
  },
  {
    slug: "autodesk",
    name: "Autodesk",
    ats: "workday",
    website: "https://www.autodesk.com",
    hq: "San Francisco, USA",
    industry: "Design Software",
    workday: { host: "autodesk.wd1.myworkdayjobs.com", tenant: "autodesk", site: "Ext" },
  },
  {
    slug: "workday",
    name: "Workday",
    ats: "workday",
    website: "https://www.workday.com",
    hq: "Pleasanton, USA",
    industry: "Enterprise Software",
    workday: { host: "workday.wd5.myworkdayjobs.com", tenant: "workday", site: "Workday" },
  },
  {
    slug: "cadence",
    name: "Cadence",
    ats: "workday",
    website: "https://www.cadence.com",
    hq: "San Jose, USA",
    industry: "EDA",
    workday: { host: "cadence.wd1.myworkdayjobs.com", tenant: "cadence", site: "External_Careers" },
  },
  {
    slug: "salesforce",
    name: "Salesforce",
    ats: "workday",
    website: "https://www.salesforce.com",
    hq: "San Francisco, USA",
    industry: "CRM",
    workday: { host: "salesforce.wd12.myworkdayjobs.com", tenant: "salesforce", site: "External_Career_Site" },
  },
  {
    slug: "paypal",
    name: "PayPal",
    ats: "workday",
    website: "https://www.paypal.com",
    hq: "San Jose, USA",
    industry: "Payments",
    workday: { host: "paypal.wd1.myworkdayjobs.com", tenant: "paypal", site: "jobs" },
  },
  {
    slug: "nxp",
    name: "NXP",
    ats: "workday",
    website: "https://www.nxp.com",
    hq: "Eindhoven, Netherlands",
    industry: "Semiconductors",
    workday: { host: "nxp.wd3.myworkdayjobs.com", tenant: "nxp", site: "careers" },
  },
  {
    slug: "kla",
    name: "KLA",
    ats: "workday",
    website: "https://www.kla.com",
    hq: "Milpitas, USA",
    industry: "Semiconductors",
    workday: { host: "kla.wd1.myworkdayjobs.com", tenant: "kla", site: "Search" },
  },
];

export const COMPANY_BY_SLUG = Object.fromEntries(
  COMPANIES.map((company) => [company.slug, company]),
) as Record<string, Company>;

export function faviconUrl(website: string): string {
  const host = new URL(website).hostname.replace(/^www\./, "");
  return `https://www.google.com/s2/favicons?domain=${host}&sz=128`;
}
